In [6]:
import numpy as np
import array as arr

In [11]:
matriz = arr.array('i',[1,2,3,4,5])

In [20]:
matriz

array([1, 2, 3])

In [16]:
matriz = np.array([1,2,3])

In [17]:
matriz

array([1, 2, 3])

In [23]:
lista = [1,3,5]
matriz = np.array([2,4,6])
print(lista)
print(matriz)

[1, 3, 5]
[2 4 6]


In [34]:
lista.remove(7)
print(lista)

[1, 3, 5, 7]
[74 76 78]


In [36]:
matriz  = matriz + np.array([8])
print(matriz)

[82 84 86]


In [39]:
a = [1,2,3]
b = [4,5,6]

In [38]:
a+b

[1, 2, 3, 4, 5, 6]

In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6]) 

In [44]:
a+b
a*b
a/b
a-b

array([-3, -3, -3])

In [46]:
m2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
m2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
lista = [1,2,3,4,5]
lista2 = [6,7,8,9,10]
matriz = np.array([lista,lista2])
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
lista = [[1,2,3],[4,5,6]]
matriz = np.array(lista)
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
m = np.arange(20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
m.shape
m.ndim
m.size

20

In [64]:
m = np.zeros((3,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
m = np.linspace(99, 88,25)
m

array([99.        , 98.54166667, 98.08333333, 97.625     , 97.16666667,
       96.70833333, 96.25      , 95.79166667, 95.33333333, 94.875     ,
       94.41666667, 93.95833333, 93.5       , 93.04166667, 92.58333333,
       92.125     , 91.66666667, 91.20833333, 90.75      , 90.29166667,
       89.83333333, 89.375     , 88.91666667, 88.45833333, 88.        ])

In [76]:
m = np.arange(27).reshape(3,3,3)
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
m = np.arange(24).reshape(4,6)
m[3,4]

22

In [80]:
m1 = np.array([90,7,9,4,2,1])
np.sort(m1)

array([ 1,  2,  4,  7,  9, 90])

In [85]:
m1 = np.array([2,3])
np.power(m1,3)
np.array(m1**3)

array([ 8, 27], dtype=int32)

In [88]:
m1 = np.array([2,3,4,5,6,7])
np.array(m1>4)

array([False, False, False,  True,  True,  True])

In [90]:
m1.max()
m1.min()

2

In [95]:
m2 = np.array([11,22,33,44,55])
np.concatenate((m1,m2))


array([ 2,  3,  4,  5,  6,  7, 11, 22, 33, 44, 55])

In [21]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

In [22]:
m1+m2
m1+2
m2*2

array([[10, 12],
       [14, 16]])

In [23]:
np.add(m1,m2)
np.subtract(m1,m2)
np.multiply(m1,m2)
np.divide(m1,m2)
m1.dot(m2)

array([[19, 22],
       [43, 50]])

In [10]:
m = np.random.randint(10, size=(3,3))
m

array([[3, 5, 1],
       [9, 9, 6],
       [3, 9, 7]])

In [19]:
m = np.random.rand(2,3)
m

array([[0.50989333, 0.77834397, 0.21425608],
       [0.39970686, 0.98599894, 0.55768392]])

In [44]:
m = np.random.choice([3,5,7,8,9,6,5,4,1],size=(2,3))
m

array([[5, 8, 7],
       [3, 4, 3]])

In [83]:
m = np.random.choice([2,4,6],p=[0.25,0.25,0.5],size=(1))
m

array([6])

In [111]:
m = np.random.choice([2,4,8,10], p =[0.3,0.5,.1,.1], size=(2))
m

array([10, 10])

In [116]:
m = np.array([[0,1,2],[4,2,3]])
np.sum(m,axis=0)

array([4, 3, 5])

In [127]:
m1 = np.array([[1,1],[1,1]])
m2 = np.array([[8,8],[8,8]])
np.concatenate([m1,m2], axis=0)


array([8, 8])

In [130]:
m1 = np.array([1,1])
m2 = np.array([8,8])
np.concatenate([m1,m2],axis=0)

array([1, 1, 8, 8])

In [151]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.amax(m,0)
np.amin(m,0)
np.ptp(m,axis=1)
np.ptp(m, axis=0)
np.percentile(m,50,axis=0)
np.percentile(m,50,axis=1)
np.median(m,axis=0)
np.mean(m,axis=0)

array([4., 5., 6.])

In [155]:
m = np.array([1,2,3,4,5,6])
np.average(m)
np.std(m)

1.707825127659933

In [157]:
m = np.array([[1,-1,2],[3,2,0]])
m

array([[ 1, -1,  2],
       [ 3,  2,  0]])

In [162]:
m1 = np.array([[1],[2],[3]])
m1 = np.array([[1, 2, 3]])
m1

array([[1, 2, 3]])

In [163]:
np.transpose(m1)

array([[1],
       [2],
       [3]])

In [172]:
a = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.array([[-3],[5],[-2]])
np.transpose(b)
x = np.linalg.solve(a,b)
np.allclose(np.dot(a,x),b)
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [173]:
m1 = np.array([[2,7,3],[2,8,2],[1,3,1]])
m2 = np.array([[1,1,0])

array([[2, 7, 3],
       [2, 8, 2],
       [1, 3, 1]])